name: Sky Tower Films
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10598
title: Sky Tower Films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2b2720'
    - '#534736'
    - '#a99d80'
    - '#dbdbcb'
  brandStrength: 0.8376115912105888
  lightness: 0.210728719830513
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
